name: secp256k1
description: "Pure secp256k1 signature algorithm implement for dart language which uses pure dart and basic types to represent all matters"
version: 0.2.1
homepage: https://github.com/c0mm4nd/dart-secp256k1

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
